name: Deploy to Hestia

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Workflows

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/contact/web/inclusiv.allopro24.com/public_html/inclusive
            echo "Pulling latest code and deploying..."
            # Mise à jour du code
            git pull origin main

            # Installation et Build directement sur le serveur
            npm install
            npm run build

            # Laravel commands
            /usr/bin/php8.3 artisan migrate --force
            /usr/bin/php8.3 artisan config:cache
            /usr/bin/php8.3 artisan view:clear
            /usr/bin/php8.3 artisan queue:restart
